config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'export', to: :export, controller: 'categories'
  post 'import', to: :import, controller: 'categories'
  get 'showall', to: :showall, controller: 'categories'
  get 'entries', to: :entry, controller: 'categories'
  get 'versions' => 'versions#index'
  get '_list_categories', to: :_list_categories, controller: 'categories'
  post 'users/action' => 'users#action'
  post 'users/chooseRole' => 'users#chooseRole'
  post 'categories/edit_description' => 'categories#edit_description'

  post 'categories/edit_description' => 'categories#edit_description'
  
 post 'categories/create-comment' => 'categories#create_comment'
  post 'categories/create-post' => 'categories#create_post'
  resources :categories do
    member do
      post :reparent, :import
      get :description
      get :details
      post :edit__description
    end
    resources :posts 
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  resourcify

  #has_paper_trail

end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  resourcify

  include NestedTree  

  has_many :articles
  has_many :comments,  :dependent => :destroy
  has_one :post,  :dependent => :destroy  
  has_paper_trail
end

app/models/comment.rb
class Comment < ApplicationRecord

  #has_paper_trail

  belongs_to :user
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord

  #has_paper_trail

  belongs_to :user  
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  #has_paper_trail

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable 

  has_many :comments
  has_many :posts

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/make_controller.rb
class MakeController < ApplicationController
  def view
    @category = Category.find(params[:category_id]);
    @post = @category.posts.build;
    @post.user = current_user
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
        @posts = Post.all
        @user = current_user
        @category = Category.all.find(params[:category_id])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @category = Category.find(params[:category_id]);
  end

  # GET /posts/new
  def new
    @category = Category.find(params[:category_id]);
    @post = @category.posts.build;
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @category = Category.find(params[:category_id]);
    @post = @category.posts.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to category_post_path(@category.id, @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to category_post_path(@post.category_id, @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:category_id, :title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end
class CatAndBook
	
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/power_helper.rb
module PowerHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/export/export.html.erb
Xin chào!

app/views/layouts/common/_banner.html.erb
<!-- BEGIN HEADER TOP -->
<div class="page-header-top">
  <div class="container">
    <!-- BEGIN LOGO -->
    <div class="page-logo">
      <a href="<%= root_path %>" style="background-color: #fff" >
        <%= image_tag('logo-wiki.png', alt: "Missing logo", class: "logo-wiki") %>
      </a>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler"></a>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <!-- BEGIN TOP NAVIGATION MENU -->
    <div class="top-menu">
      <ul class="nav navbar-nav pull-right">
        <%= render "layouts/common/login_items" %>
      </ul>
    </div>
    <!-- END TOP NAVIGATION MENU -->
  </div>
</div>
<!-- END HEADER TOP -->

app/views/layouts/common/_flash.html.erb
<% unless flash.blank? %>
<div id='flash'>
  <% flash.each do |key, value| %>
  <div class='flash alert alert-dismissible fade in alert-<%= key == 'notice' ? 'info' : 'danger' %>'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
      <span aria-hidden='true'>&times;</span>
    </button>
    <%= value %>
  </div>
  <% end %>
</div>
<% end %>

app/views/layouts/common/_footer.html.erb
<!-- BEGIN FOOTER -->
<!-- BEGIN PRE-FOOTER -->
<div class="page-prefooter">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
        <h2>About</h2>
        <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam dolore. </p>
      </div>
      <div class="col-md-3 col-sm-6 col-xs12 footer-block">
        <h2>Subscribe Email</h2>
        <div class="subscribe-form">
          <form action="javascript:;">
            <div class="input-group">
              <input type="text" placeholder="mail@email.com" class="form-control">
              <span class="input-group-btn">
                <button class="btn" type="submit">Submit</button>
              </span>
            </div>
          </form>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
        <h2>Follow Us On</h2>
        <ul class="social-icons">
          <li>
            <a href="javascript:;" data-original-title="rss" class="rss"></a>
          </li>
          <li>
            <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
          </li>
          <li>
            <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
          </li>
          <li>
            <a href="javascript:;" data-original-title="googleplus" class="googleplus"></a>
          </li>
          <li>
            <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
          </li>
          <li>
            <a href="javascript:;" data-original-title="youtube" class="youtube"></a>
          </li>
          <li>
            <a href="javascript:;" data-original-title="vimeo" class="vimeo"></a>
          </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
        <h2>Contacts</h2>
        <address class="margin-bottom-40"> Phone: 800 123 3456
          <br> Email:
          <a href="mailto:info@metronic.com">info@metronic.com</a>
        </address>
      </div>
    </div>
  </div>
</div>
<!-- END PRE-FOOTER -->
<!-- BEGIN INNER FOOTER -->
<div class="page-footer">
  <div class="container"> 2016 &copy; Vietnam National University, Hanoi
  </div>
</div>
<div class="scroll-to-top">
  <i class="icon-arrow-up"></i>
</div>
<!-- END INNER FOOTER -->
<!-- END FOOTER -->

app/views/layouts/common/_header.html.erb
<!-- BEGIN HEADER -->
<div class="page-header">
  <%= render 'layouts/common/banner' %>
  <%= render 'layouts/common/navbar' %>
</div>
<!-- END HEADER -->

app/views/layouts/common/_login_items.html.erb
<% if user_signed_in? %>
  <!-- BEGIN NOTIFICATION DROPDOWN -->
  <!-- END NOTIFICATION DROPDOWN -->
  <!-- BEGIN TODO DROPDOWN -->
  <!-- END TODO DROPDOWN -->
  <!-- BEGIN INBOX DROPDOWN -->
  <li class="dropdown dropdown-extended dropdown-inbox dropdown-dark" id="header_inbox_bar">
    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
      <span class="circle">3</span>
      <span class="corner"></span>
    </a>
    <ul class="dropdown-menu">
      <li class="external">
        <h3>You have
          <strong>7 New</strong> Messages</h3>
        <a href="app_inbox.html">view all</a>
      </li>
      <li>
        <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
          <li>
            <a href="#">
              <span class="photo">
                <img src="" class="img-circle" alt=""> </span>
                <span class="subject">
                  <span class="from"> Richard Doe </span>
                  <span class="time">16 mins </span>
                </span>
                <span class="message"> Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </li>
  <!-- END INBOX DROPDOWN -->
  <!-- BEGIN USER LOGIN DROPDOWN -->
  <li class="dropdown dropdown-user dropdown-dark">
    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
      <img alt="" class="img-circle" src="<%= image_url "avatar.png" %>">
      <span class="username username-hide-mobile" style="text-decoration: none;"><%=@user.email%></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-default">
      <li>
        <% profile = "/users/" + @user.id.to_s %>
        <a href=<%=profile%> >
          <i class="icon-user"></i> My Profile </a>
      </li>
      <li>
        <a href="<%= destroy_user_session_path %>">
          <i class="icon-key"></i> Log Out </a>
      </li>
    </ul>
  </li>
<% else %>
  <li class="dropdown dropdown-extended">
    <%= button_to "Đăng ký", new_user_registration_path, method: "get", class: "btn btn-circle btn-default" %>
  </li>
  <li class="dropdown dropdown-extended">
    <%= button_to "Đăng nhập", new_user_session_path, method: "get", class: "btn btn-circle btn-success" %>
  </li>
<% end %>
<!-- END USER LOGIN DROPDOWN -->
<!-- BEGIN QUICK SIDEBAR TOGGLER -->
<!-- END QUICK SIDEBAR TOGGLER -->

app/views/layouts/common/_navbar.html.erb
<!-- BEGIN HEADER MENU -->
<div class="page-header-menu">
  <div class="container">
    <!-- BEGIN HEADER SEARCH BOX -->
    <form class="search-form" action="page_general_search.html" method="GET">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="query">
        <span class="input-group-btn">
          <a href="javascript:;" class="btn submit">
            <i class="icon-magnifier"></i>
          </a>
        </span>
      </div>
    </form>
    <!-- END HEADER SEARCH BOX -->
    <!-- BEGIN MEGA MENU -->
    <!-- DOC: Apply "hor-menu-light" class after the "hor-menu" class below to have a horizontal menu with white background -->
    <!-- DOC: Remove data-hover="dropdown" and data-close-others="true" attributes below to disable the dropdown opening on mouse hover -->
    <div class="hor-menu">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page? root_path %>">
          <a href="<%= root_path %>" class="nav-link">
            <i class="icon-home"></i> Trang chủ
          </a>
        </li>
        <li class="<%= "active" if current_page? categories_path %>">
          <a href="<%= showall_path %>" class="nav-link">
            Xem chuyên mục
          </a>
        </li>
        <li aria-haspopup="true" class="menu-dropdown classic-menu-dropdown ">
          <a href="/entries"> Mục từ
            <span class="arrow"></span>
          </a>

          
        </li>
        <% if current_user != nil %>

        <% if current_user.roles.exists?(:name => "admin")  %>
        <li class="<%= "active" if current_page? categories_path %>">
          <a href="<%= users_path %>" class="nav-link">
            Phân quyền tài khoản
          </a>
        </li>
        <% end %>
        <% end %>
      </ul>
    </div>
    <!-- END MEGA MENU -->
  </div>
</div>
<!-- END HEADER MENU -->