config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'export', to: :export, controller: 'categories'
  post 'import', to: :import, controller: 'categories'
  get 'showall', to: :showall, controller: 'categories'
  get 'entries', to: :entry, controller: 'categories'
  get 'versions' => 'versions#index'
  get '_list_categories', to: :_list_categories, controller: 'categories'
  post 'users/action' => 'users#action'
  post 'users/chooseRole' => 'users#chooseRole'
  post 'categories/edit_description' => 'categories#edit_description'

  post 'categories/edit_description' => 'categories#edit_description'
  
 post 'categories/create-comment' => 'categories#create_comment'
  post 'categories/create-post' => 'categories#create_post'
  resources :categories do
    member do
      post :reparent, :import
      get :description
      get :details
      post :edit__description
    end
    resources :posts 
    resources :comments
  end

end

app/models/post.rb
class Post < ApplicationRecord

  #has_paper_trail

  belongs_to :user  
  belongs_to :category
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
        @posts = Post.all
        @user = current_user
        @category = Category.all.find(params[:category_id])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @category = Category.find(params[:category_id]);
  end

  # GET /posts/new
  def new
    @category = Category.find(params[:category_id]);
    @post = @category.posts.build;
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @category = Category.find(params[:category_id]);
    @post = @category.posts.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to category_post_path(@category.id, @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to category_post_path(@post.category_id, @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:category_id, :title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
        @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @category = Category.find(params[:category_id]);
  end

  # GET /posts/new
  def new
    @category = Category.find(params[:category_id]);
    @post = @category.posts.build;
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @category = Category.find(params[:category_id]);
    @post = @category.posts.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to category_post_path(@category.id, @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to category_post_path(@post.category_id, @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:category_id, :title, :body)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/post/_form.html.erb
<%= simple_form_for @post, :url => category_post_path(category_id: post.category_id, id: post.id) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :category_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/post/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post%>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/post/index.html.erb
<p id="notice">
   <%= notice %>
</p>
<h1>
   <%= @category.name %>
</h1>
<div style="margin-left: 15px; margin-top: 20px;">
   <div class="c-comment-list" id="list-coment">
      <div class="media">
         <div class="media-left">
            <a href="#">
            <img class="media-object media-avatar" alt="" src="<%= image_url "avatar.png" %>"> 
            </a>
         </div>
         <div class="media-body">
            <h4 class="media-heading" style="margin-top: 10px;">
               <a href="#" class="username" >
               <%=@user.email%>
               </a> 
               <br>
               <h1 class="blog-single-head-title">
               </h1>
            </h4>
            <div style="margin-left: 20px;">
               <div class="blog-single-desc">
                  <div class="md-editor active" id="1517505640080">
                     <div class="md-header btn-toolbar">
                        <div class="btn-group">
                           <button class="btn-default btn-sm btn" type="button" title="Bold" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdBold" data-hotkey="Ctrl+B">
                           <span class="glyphicon glyphicon-bold">
                           </span> </button>
                           <button class="btn-default btn-sm btn" type="button" title="Italic" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdItalic" data-hotkey="Ctrl+I">
                           <span class="glyphicon glyphicon-italic">
                           </span> </button>
                           <button class="btn-default btn-sm btn" type="button" title="Heading" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdHeading" data-hotkey="Ctrl+H">
                           <span class="glyphicon glyphicon-header">
                           </span> </button>
                        </div>
                        <div class="btn-group">
                           <button class="btn-default btn-sm btn" type="button" title="URL/Link" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdUrl" data-hotkey="Ctrl+L">
                           <span class="glyphicon glyphicon-link">
                           </span> </button>
                           <button class="btn-default btn-sm btn" type="button" title="Image" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdImage" data-hotkey="Ctrl+G">
                           <span class="glyphicon glyphicon-picture">
                           </span> </button>
                        </div>
                        <div class="btn-group">
                           <button class="btn-default btn-sm btn" type="button" title="Unordered List" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdList" data-hotkey="Ctrl+U">
                           <span class="glyphicon glyphicon-list">
                           </span> </button>
                           <button class="btn-default btn-sm btn" type="button" title="Ordered List" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdListO" data-hotkey="Ctrl+O">
                           <span class="glyphicon glyphicon-th-list">
                           </span> </button>
                           <button class="btn-default btn-sm btn" type="button" title="Code" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdCode" data-hotkey="Ctrl+K">
                           <span class="glyphicon glyphicon-asterisk">
                           </span> </button>
                           <button class="btn-default btn-sm btn" type="button" title="Quote" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdQuote" data-hotkey="Ctrl+Q">
                           <span class="glyphicon glyphicon-comment">
                           </span> </button>
                        </div>
                        <div class="btn-group">
                           <button class="btn-sm btn btn-primary" type="button" title="Preview" tabindex="-1" data-provider="bootstrap-markdown" data-handler="bootstrap-markdown-cmdPreview" data-hotkey="Ctrl+P" data-toggle="button">
                           <span class="glyphicon glyphicon-search">
                           </span> Preview</button>
                        </div>
                        <div class="md-controls">
                        </div>
                     </div>
                     <textarea name="markdown" data-provide="markdown" rows="10" data-error-container="#editor_error" class="md-input" style="resize: none; width: 100%;">
               </textarea>
                     <div class="md-fullscreen-controls">
                     </div>
                  </div>
                  <div class="form-actions" style="margin-top: 30px">
                                                                <div class="row">
                                                                    <div class="col-md-offset-3 col-md-9">
                                                                        <button type="submit" class="btn green">Submit</button>
                                                                        <button type="button" class="btn default">Cancel</button>
                                                                    </div>
                                                                </div>
                                                            </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<br>

app/views/post/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/post/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @post.category_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<br>

<div id="comments">
  <%= render :partial => @post.comments%>
</div>

<%= form_for [@category, @post, Comment.new] do |f|%>
    <div class="field">
      <%= f.text_area :body, class: "form_control"%>
    </div>
    <br>
    <%= f.submit "Add Comment", class: "btn btn-primary"%>
<% end %>

<%= link_to 'Edit', edit_category_post_path(@post) %> |
<%= link_to 'Back', posts_path %>