config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'export', to: :export, controller: 'categories'
  post 'import', to: :import, controller: 'categories'
  get 'showall', to: :showall, controller: 'categories'
  get 'entries', to: :entry, controller: 'categories'
  get 'versions' => 'versions#index'
  get '_list_categories', to: :_list_categories, controller: 'categories'
  post 'users/action' => 'users#action'
  post 'users/chooseRole' => 'users#chooseRole'
  post 'categories/edit_description' => 'categories#edit_description'

  post 'categories/edit_description' => 'categories#edit_description'
  
 post 'categories/create-comment' => 'categories#create_comment'
  post 'categories/create-post' => 'categories#create_post'
  resources :categories do
    member do
      post :reparent, :import
      get :description
      get :details
      post :edit__description
    end
    resources :posts 
    resources :comments
  end

end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  resourcify

  include NestedTree  

  has_many :articles
  has_many :comments,  :dependent => :destroy
  has_one :post,  :dependent => :destroy  
  has_paper_trail
end

app/controllers/categories_controller.rb
require "export_excel.rb"
require "import_excel.rb"
require 'pry'

class CategoriesController < ApplicationController
  before_action :authenticate_user!
  include ExportExcel, ImportExcel

  def index
    scope = policy_scope(Category)
    @editable = scope != nil
    gon.editable = @editable
    if not scope
      flash[:error] = "You must have a role to access this section!"
      redirect_to '/'
    else
      @categories = scope.nested_tree
    end

  end

  def show
    scope = policy_scope(Category)
    @editable = scope != nil
    gon.editable = @editable
    @categoriesDB =Category.all
    @book_name = @categoriesDB.find(params[:id]).name
    @categories_tmp= Array.new
    if scope != nil 
      @categories = scope.nested_tree
      @categories.each do |scp|
        @category_tmp = scp[:node]
        puts @category_tmp.id.to_s + " " + params[:id].to_s
      while @category_tmp.parent_id != nil
        puts @category_tmp.id.to_s + " " + params[:id].to_s
        @category_tmp = @categoriesDB.find(@category_tmp.parent_id)
      end
      if  @category_tmp.id == params[:id].to_i
        @categories_tmp.push scp
      end
      end
      @categories = @categories_tmp
      @categories_list = Array.new
      @entries_list = Array.new
      @categories.each do |category|
      @categories_list.push category[:node].name
      @name_tmp = category[:node].name + " / "
      if not category[:children].empty?  
        category[:children].each do |n|  
          categories_list_simple(@categories_list, n, @name_tmp, @entries_list)
        end
      else
        @entries_list.push category[:node].name
      end 
    end
    @entries_list.sort_by! { |m| m }
    end
    # puts "================"
    # @cr_category = Category.find(params[:id])
    # @hasRole = false
    # @categoriesNT = scope.nested_tree
    # @categoriesNT.each do |scp|
    #   puts scp[:node].id.to_s + " " + @cr_category.id.to_s
    #   if scp[:node].id == @cr_category.id
    #     if @categories.empty?
    #         @categories.push scp
    #       end
    #     @hasRole = true
    #   end
    #   puts @hasRole
    #   while @cr_category.parent_id != nil
    #     @cr_category= @categoriesDB.find(@cr_category.parent_id)
    #   puts scp[:node].id.to_s + " " + @cr_category.id.to_s
    #     if scp[:node].id == @cr_category.id
    #       if @categories.empty?
    #         @categories.push scp
    #       end
    #       puts scp[:node].id
    #       @hasRole = true
    #       break
    #     end
    #   end
    # end
    # puts @hasRole
    if scope == nil or (@categories.empty? and !@hasRole)
      flash[:error] = "You must have this role to access this section!"
      redirect_to '/'
    end

  end

  def showall
    @categories = Category.all.nested_tree
    @categories_list = Array.new
    @entries_list = Array.new
    @categories.each do |category|
      @categories_list.push category[:node].name
      @name_tmp = category[:node].name + " / "
      if not category[:children].empty?  
        category[:children].each do |n|  
          categories_list_simple(@categories_list, n, @name_tmp, @entries_list)
        end
      else
        @entries_list.push category[:node].name
      end 
    end
    @entries_list.sort_by! { |m| m }
  end

  def categories_list_simple(categories_list, all_categories, name_tmp,entries_list)
    name_tmp += all_categories[:node].name
    categories_list.push name_tmp
    if not all_categories[:children].empty? 
      name_tmp += " / "
      all_categories[:children].each do |n|
        categories_list_simple(categories_list, n, name_tmp, entries_list)
      end 
    else
        @entries_list.push all_categories[:node].name
    end 
  end



  def details
      @category = Category.find(params[:id])  
      @description = Category.find(params[:id]).description    
      @post = Post.find_by(:category_id => params[:id])
      @comments = Comment.all
      @users = User.all
      @description_comment = Array.new
      @comments.each do |comment|
      #if comment.resource_type == 'Description'
        @description_comment.push comment
      #end
    end
  end

  


 def description
    @categories = Category.all
    @category = @categories.find(params[:id])
    @name = @category.name
    @check =check_edit_description(params[:id])
    @isEntry = (@category.children_count==0)
    @description = @category.description
    @comments = Comment.all
    @users = User.all
    @description_comment = Array.new
    @havePost = true
    if @isEntry
      @post = @category.post
      if @post == nil
        @havePost = false
      end
    end
    @comments.each do |comment|
      if comment.category_id == @category.id
        @description_comment.push comment
      end
    end
  end


  def edit__description

  end 

  def edit_description
    @value = params[:data_value]
    @value = @value[1,@value.length-2]
    @arrvalue = Array.new
    @arrvalue = @value.split(',', 2)
    @check = check_edit_description(@arrvalue[0].to_i)
    if(@check)
      @description = @arrvalue[1][1,@arrvalue[1].length-2]
      @categories = Category.all
      @categories.find(@arrvalue[0]).update(description: @description)
    end

  end

  def check_edit_description(description_id)
    scope = policy_scope(Category)
    if scope == nil
      return false
    end
    @categories_scope = scope.nested_tree
    @categories = Category.all
    @categories_scope.each do |category|
      @category_tmp = @categories.find(description_id)
      while (@category_tmp.parent_id != nil)
        if category[:node].id == @category_tmp.id
          return true
        end
        @category_tmp = @categories.find(@category_tmp.parent_id)
      end   
      if category[:node].id == @category_tmp.id
        return true
      end 
    end
    return false
  end

   def create_comment
    @comment_post = params[:data_value]
    @comment_post = @comment_post[1..(@comment_post.length-2)]
    @arrvalue = Array.new
    @arrvalue = @comment_post.split(',');
    @arrvalue[1] = @arrvalue[1][1..(@arrvalue[1].length-2)]
    if @arrvalue[1] != ""
      @comment = Comment.new
      @comment.category_id = @arrvalue[0]
      @comment.body = @arrvalue[1]
      @comment.user = current_user
      @comment.save!
    end

    # filename = ExcelParser.exportData()
    # flash[:error] = "You must have this role to access this section!"
      
    # render :description
  end

  def entry
    render "application/navbar"
  end

  def create_post

    @post_JS = params[:data_value]
    @post_JS = @post_JS[1..(@post_JS.length-2)]
    @arrvalue = Array.new
    @arrvalue = @post_JS.split(',');
    @arrvalue[1] = @arrvalue[1][1..(@arrvalue[1].length-2)]

    @arrvalue[2] = @arrvalue[2][1..(@arrvalue[2].length-2)]
    if @arrvalue[1] != ""
      if Post.exists?(category_id: @arrvalue[0])
        @post = Post.find_by(category_id: @arrvalue[0])
        puts @post
      else
        @post = Post.new
      end
      @post.category_id = @arrvalue[0]
      @post.body = @arrvalue[1]
      @post.title = @arrvalue[2]
      @post.user = current_user
      @post.save!
    end

    # filename = ExcelParser.exportData()
    # flash[:error] = "You must have this role to access this section!"
      
    # render :description
  end

  def create
    @categories = Category.all
    @category = Category.new category_params
    @parent = @categories.find(@category.parent_id)
    #binding.pry
    authorize @category
    @category.save!
    @category.move_to_child_of(@parent)
    @parent.children_count += 1;
    @parent.save!
    @roles = Role.all
    @role = Role.new
    @role.name = 'editor'
    @role.resource_type = 'Category'
    @role.resource_id = @category.id
    @role.save!
    

    # filename = ExcelParser.exportData()
    # flash[:error] = "You must have this role to access this section!"
      
    # render :showall

  end


  def update
    cat = Category.find(params[:id])
    authorize cat
    cat.update! category_params
  end

  def destroy
    @categories = Category.all
    cat = Category.find(params[:id])
    @parent = @categories.find(cat.parent_id)
    @parent.children_count = @parent.children_count - 1 
    @parent.save!
    authorize cat
    cat.destroy!
  end

  def reparent

    cat = Category.find params[:id]    
    authorize cat

    version = PaperTrail::Version.new
    version.item_type = "Category"
    version.item_id = params[:id]
    version.event = "update"
    version.whodunnit = current_user.id    
    version.object = "---\n" + "id: " + cat.name + "\nparent_id: " + cat.parent_id.to_s + "\nlft: " + cat.lft.to_s + "\nrgt: " + cat.rgt.to_s + "\ndescription: " + cat.description.to_s + "\ndepth: " + cat.depth.to_s + "\nchildren_count: " + cat.children_count.to_s+ "\ncreated_at: " + cat.created_at.to_s
    #version.object = cat.parent_id
    #+ "\nparent_id: " + cat.parent_id + "\nlft: " + cat.lft + "\nrgt: " + cat.rgt + "\ndescription: " + cat.description + "\ndepth: " + cat.depth + "\nchildren_count: " + cat.children_count
    version.save

    parent_id = params.require :parent_id
    parent_cat = Category.find parent_id
    cat.move_to_child_of parent_cat    
  end

  def undo
    version = Version.last
    
    @categories = Category.all
    cat = Category.order(updated_at: :desc).limit(1)
    @parent = @categories.find(cat.parent_id)
    @parent.children_count = @parent.children_count + 1
    @parent.save!
    authorize cat
    cat.destroy!
  end

  def export
    filename = ExportExcel.export_data
    send_file Rails.root.join('export', filename), :type=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet ", :x_sendfile=>true
    # render "export/export"
  end

  def import
    upload_file = params[:upload][:datafile]
    saved_file_path = Rails.root.join('uploads', upload_file.original_filename)

    File.open(saved_file_path, 'wb') do |file|
      file.write(upload_file.read)
    end

    ImportExcel.import_data(upload_file.original_filename)

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_list_categories.html.erb
<div class="portlet light portlet-fit ">
    <div class="portlet-body">
        <div class="mt-element-list">
            <div class="mt-list-head list-simple font-white bg-green">
                <div class="list-head-title-container">
                <h4 class="list-title">Categories List</h4>
                </div>
            </div>
            <div class="mt-list-container list-simple" >
                <ul>
                    <%@categories_list.each do |cat|%>
                    <li class="mt-list-item" style="padding: 0px 0px">
                        <div class="list-item-content" >
                            <h5 >
                                <a href="javascript:;"><%=cat%></a>
                            </h5>
                        </div>
                    </li>

                    <% end -%>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/categories/_list_entries.html.erb
<div class="portlet light portlet-fit ">
    <div class="portlet-body">
        <div class="mt-element-list">
            <div class="mt-list-head list-simple font-white bg-green">
                <div class="list-head-title-container">
                <h4 class="list-title">Categories List</h4>
                </div>
            </div>
            <div class="mt-list-container list-simple" >
                <ul>
                    <%@entries_list.each do |entry|%>
                    <li class="mt-list-item" style="padding: 0px 0px">
                        <div class="list-item-content" >
                            <h5 >
                                <a href="javascript:;"><%=entry%></a>
                            </h5>
                        </div>
                    </li>

                    <% end -%>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/categories/_show_categories.html.erb
<div class="portlet light ">
  <div class="clearfix">
    <div class="btn-group" data-toggle="buttons" style="float: right;">
      <label class="btn green active" onclick="choose_view(1)">
        <input type="radio" class="toggle" > Tree
      </label>
      <label class="btn green" onclick="choose_view(2)">
        <input type="radio" class="toggle" > List Categories
      </label>
      <label class="btn green" onclick="choose_view(3)">
        <input type="radio" class="toggle" > List Entries
      </label>
    </div>
  </div>
  <div id="view_list">
    <div id="list_tree">
      <%= render partial: 'tree_list_categories'-%>
    </div>
    <div id="list_simple" style="display: none;">
      <%= render partial: 'list_categories'-%>
    </div>
    <div id="list_entries" style="display: none;">
      <%= render partial: 'list_entries'-%>
    </div>
  </div>
</div>
<div>
  <%= form_tag('ahihi', remote: true) do %>
  <% end %>
</div>

app/views/categories/_tree.html.erb
  <li data-category-id="<%= tree[:node].id %>">
  	<%= tree[:node].name %>
  <% if not tree[:children].empty? %>
  <ul>
    <% tree[:children].each do |n| %>
    <%= render :partial => "tree_children", :object => n -%>

    <% end %>
  </ul>
  <% end %>
</li>
<% if params[:id].to_i >= tree[:node].lft.to_i and params[:id].to_i <= tree[:node].rgt.to_i %>
    <% end %>

app/views/categories/_tree_children.html.erb
	<li data-category-id="<%= tree_children[:node].id %>">	
  	<%= tree_children[:node].name %>
  <% if not tree_children[:children].empty? %>
      <ul>
        <% tree_children[:children].each do |n| %>
            <%= render :partial => "tree_children", :object => n -%>

        <% end %>
      </ul>
  <% end %>
</li>
<% if params[:id].to_i >= tree_children[:node].lft.to_i and params[:id].to_i <= tree_children[:node].rgt.to_i %>

 <% end -%>

app/views/categories/_tree_list_categories.html.erb
<div class="portlet light portlet-fit ">
	<div class="portlet-body">
		<div class="mt-element-list">
			<div class="mt-list-head list-simple font-white bg-green">
				<div class="list-head-title-container">
					<h4 class="list-title">Categories Tree</h4>
				</div>
			</div>
			<div class="portlet-body" >
				<button type="button" class="btn red-sunglo " onclick="view_description();" style="float: right;">
					 Mô tả
				</button>
				<div id="categories">
					<ul><% @categories.each do |cat| %>	
						<%= render partial: 'tree', object: cat -%>
						<% end %></ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/categories/description.html.erb
<% content_for :title do %>

            <%=@name%>
<% end %>

<div class="col-md-11">
   <div class="blog-content-2">
      <div class="blog-single-content bordered blog-container">
<div class="col-md-12">
   <div class="col-md-1"></div>
   
   <div class="col-md-3"></div>
   </div>
   <div></div>
   <br>


         <div class="blog-comments" style="background-color: #fff; padding: 5% 5% 5% 5%">
            <h3 class="sbold blog-comments-title" style="margin: 20px 0px 50px 0px">Mô tả</h3>
   <div class="c-comment-list" >
                  <div class="media">
                     <div class="media-body">
                        <div style="margin-left: 20px;"><div class="blog-single-desc" id="post_body">
      <div class="portlet box green" style="width: 85%; border: 1px solid #5cd1db" >
      
      <div class="portlet-body">
         <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;" id="description">
            <div class="scroller" style="height: 200px; overflow: hidden; width: auto;" data-initialized="1">
               <br> 
               <span id="description_text"><%=@description%></span>
            </div>
            <div class="slimScrollBar" style="background: rgb(187, 187, 187); width: 7px; position: absolute; top: 25px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px; height: 175.439px;">
            </div>
            <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(234, 234, 234); opacity: 0.2; z-index: 90; right: 1px;">
            </div>
         </div>
         <div class="form-group form-md-line-input form-md-floating-label" id="edit_description" style="display: none;">
            <textarea class="form-control" rows="8" id="description_area"><%=@description%></textarea>
         </div>
      </div>
   </div>
   </div>
</div>
<% if @check %>
         <div class="actions">
            <button class="btn blue btn-block " style="width: 10%; margin-top: 30px;" 
            onclick="edit_save(<%=params[:id]%>)" > 
            <i class="fa fa-edit" id="icon_edit"></i> 
            <span id="edit_save">Sửa</span>
            </button>
         </div>
         <% end %>
   
                     </div>
                  </div>
               </div>
            <% if @isEntry %>
            <h3 class="sbold blog-comments-title" style="margin: 20px 0px 50px 0px">Post</h3>
            <% if @havePost %>
            <div id="havePost" >
               <div class="c-comment-list" >
                  <div class="media">
                     <% link = "/users/" + @post.user.id.to_s%>
                     <div class="media-left">
                        <a href=<%=link%>>
                        <img class="media-object media-avatar" alt="" src="<%= image_url "avatar.png" %>"> 
                        </a>
                     </div>
                     <div class="media-body">
                        <h4 class="media-heading">
                           <a href=<%=link%> class="username"><%=@post.user.email%></a> 
                           <br>
                           <div class="time_comment">
                              <i class="icon-calendar font-blue"></i>
                              <span class="c-date"><%= @post.created_at %></span>
                           </div>
                           <h1 class="blog-single-head-title" id="post_tittle"><%= @post.title %></h1>
                        </h4>
                        <div style="margin-left: 20px;"><div class="blog-single-desc" id="post_body">
      <%= @post.body %>
   </div></div>
   <button class="btn blue btn-block " style="width: 10%; margin-top: 30px;" 
            onclick="editPost()"> 
            <i class="fa fa-edit"></i> Sửa
            </button>
                     </div>
                  </div>
               </div>
            </div>
            <% else %>
            <div id="noPost">
            <div style="margin-top: -20px; margin-bottom: 20px;color: red; " class="sbold blog-comments-title" >Chưa có post! Vui lòng tạo Post</div>
      
            <button class="btn blue btn-block " style="width: 10%;" 
            onclick="createPost()"> 
            <i class="fa fa-edit"></i> Viết
            </button>
            </div>
            
            <% end -%>
            <form action="#" style="display: none;" id="form_post">
      <div class="form-group"  >
         <input type="text" name="" placeholder="Write title here ..." id="tittle">
         <label style="color: red" id="requireTit"></label>
         <textarea rows="8" name="message" placeholder="Write post here ..." class="form-control c-square" id="post" required="required"></textarea>
         <label style="color: red" id="requirePost"></label>
      </div>
      <div class="form-group">
         <button type="button" class="btn blue"onclick="create_post(<%=params[:id]%>)">Submit</button>
      </div>
   </form>
            <% end -%>
            <hr class="hr-description">
            <h3 class="sbold blog-comments-title" style="margin: 50px 0px 50px 0px">Comments(<%= @description_comment.length %>)</h3>
            <%= render "comments/comment_created.html" %>
         </div>
      </div>
   </div>
</div>

app/views/categories/details.html.erb
<% content_for :title do %>
Mô tả
<% end %>
<div class="col-md-12">
  <div class="col-md-1"></div>
  <div class="portlet box green col-md-8" style="width: 70%">
    <div class="portlet-title">
      <div class="caption">
        <i class="fa fa-gift">
        </i>
        <%=@name%>
      </div>
      <% if @check %>
      <div class="actions">
        <a href="javascript:;" class="btn white" onclick="edit_save(<%=params[:id]%>)">
          <i class="fa fa-pencil">
          </i> 
          <span id="edit_save" >Edit</span>
        </a>
      </div>
      <% end %>
    </div>
    <div class="portlet-body">
      <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;" id="description">
        <div class="scroller" style="height: 200px; overflow: hidden; width: auto;" data-initialized="1">
          <br> 
          <span id="description_text"><%=@description%></span>
        </div>
        <div class="slimScrollBar" style="background: rgb(187, 187, 187); width: 7px; position: absolute; top: 25px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px; height: 175.439px;">
        </div>
        <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(234, 234, 234); opacity: 0.2; z-index: 90; right: 1px;">
        </div>
      </div>
      <div class="form-group form-md-line-input form-md-floating-label" id="edit_description" style="display: none;">
        <textarea class="form-control" rows="8" id="description_area"><%=@description%></textarea>
      </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>
<% if @post %>
<p>
  <strong>Category:</strong>
  <%= @post.category_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<br>

<div id="comments">
  <%= render :partial => @post.comments%>
</div>

<%= form_for [@category, @post, Comment.new] do |f|%>
    <div class="field">
      <%= f.text_area :body, class: "form_control"%>
    </div>
    <br>
    <%= f.submit "Add Comment", class: "btn btn-primary"%>
<% end %>
<%end%>
<div class="col-md-11">
  <div class="blog-content-2">
    <div class="blog-single-content bordered blog-container">
      <div class="blog-comments" style="background-color: #fff; padding: 5% 5% 5% 5%">
        <h3 class="sbold blog-comments-title" style="margin: 20px 0px 50px 0px">Comments(<%= @description_comment.length %>)</h3>
        <%= render "comments/comment_created.html" %>
        
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<% content_for :title do %>
Quản lý chuyên mục
<% end %>
  
<div class="portlet light ">
  <% if @editable %>

  <div class="portlet-title">
    <div class="title">

    </div>
    <div class="actions">
      <div class="btn-group">
        <%= form_tag({:controller => "categories", :action => "import"}, {:multipart => true, :style => "display:none", :id => "upload-form"}) do %>
        
            <%= file_field 'upload', 'datafile' %>
            <%= submit_tag "Upload", :id => "start_uploading" %>
        <% end %>
        <button type="submit" class="btn btn-success btn-sm" onclick="undo();">
          Restore
        </button>
        <button type="submit" class="btn btn-success btn-sm" onclick="uploadfile();">
          <i class="fa fa-upload" aria-hidden="true"></i> Nhập
        </button>
        <a href="<%= export_path %>" class="btn btn-info btn-sm">
            <i class="fa fa-download" aria-hidden="true"></i> Xuất
        </a>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-success btn-sm" onclick="view_posts();">
          <i class="fa fa-plus" aria-hidden="true"></i> Xem bài viết
        </button>
        <button type="button" class="btn btn-success btn-sm" onclick="create_child();">
          <i class="fa fa-plus" aria-hidden="true"></i> Tạo chuyên mục con
        </button>
        <button type="button" class="btn btn-info btn-sm" onclick="rename_node();">
          <i class="fa fa-pencil" aria-hidden="true"></i> Đổi tên
        </button>
        <button type="button" class="btn btn-danger btn-sm" onclick="delete_node();">
          <i class="fa fa-trash" aria-hidden="true"></i> Xóa
        </button>
      </div>
    </div>
  </div>
  <% end %>
  <div class="portlet-body">
    <div id="categories">
      <ul><% @categories.each do |cat| %>
        <%= render partial: 'tree', object: cat -%>
      <% end %></ul>
    </div>
  </div>
</div>
</div>
<div>
  <%= form_tag('ahihi', remote: true) do %>
  <% end %>
</div>
<nav class="context-menu">
  <ul class="context-menu__items">
    <li class="context-menu__item" id="item-first">
    </li>
    <li class="context-menu__item" >
      <a href="#" class="context-menu__link">
         Open in new tab
      </a>
    </li>
    <li class="context-menu__item" >
      <%=link_to 'View Comment',  category_posts_path(category_id:2)  %>
    </li>
    <li class="context-menu__item">
      <a href="#" class="context-menu__link">
        <i class="fa fa-edit"></i> dd comment
      </a>
    </li>
    <li class="context-menu__item" >
      <a href="#" class="context-menu__link">
        <i class="fa fa-times"></i> Delete category
      </a>
    </li>
    <li class="context-menu__item" id="item-last">
    </li>
  </ul>
</nav>

app/views/categories/show.html.erb
<% content_for :title do %>
  <%=@book_name%>
<% end %>
<div class="portlet light ">
  <% if @editable %>
  <div class="portlet-title">
    <div class="title">  
    </div>
    <div class="actions">
      <div class="btn-group">
        <%= form_tag({:controller => "categories", :action => "import"}, {:multipart => true, :style => "display:none", :id => "upload-form"}) do %>
        <%= file_field 'upload', 'datafile' %>
        <%= submit_tag "Upload", :id => "start_uploading" %>
        <% end %>
        <button type="submit" class="btn btn-success btn-sm" onclick="uploadfile();">
          <i class="fa fa-upload" aria-hidden="true"></i> Nhập
        </button>
        <a href="<%= export_path %>" class="btn btn-info btn-sm">
          <i class="fa fa-download" aria-hidden="true"></i> Xuất
        </a>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-success btn-sm" onclick="view_posts();">
          <i class="fa fa-plus" aria-hidden="true"></i> Xem bài viết
        </button>
        <button type="button" class="btn btn-success btn-sm" onclick="create_child();">
          <i class="fa fa-plus" aria-hidden="true"></i> Tạo chuyên mục con
        </button>
        <button type="button" class="btn btn-info btn-sm" onclick="rename_node();">
          <i class="fa fa-pencil" aria-hidden="true"></i> Đổi tên
        </button>
        <button type="button" class="btn btn-danger btn-sm" onclick="delete_node();">
          <i class="fa fa-trash" aria-hidden="true"></i> Xóa
        </button>
        
      </div>
    </div>
  </div>
  <% end %>
  
  <%= render partial: 'show_categories'-%>
</div>

<div>
  <%= form_tag('ahihi', remote: true) do %>
  <% end %>
</div>

app/views/categories/showall.html.erb
<% content_for :title do %>
Xem chuyên mục
<% end %>
<%= render partial: 'show_categories'-%>
<div>
  <%= form_tag('ahihi', remote: true) do %>
  <% end %>
</div>